# Generated by Django 4.2.7 on 2023-11-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='email',
            field=models.EmailField(default='user@gmail.com', max_length=277, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='consumer_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Blog Post'),
        ),
    ]
