# Generated by Django 4.2.7 on 2023-11-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_consumer_content_alter_consumer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='content'),
        ),
    ]
